### ISSUE TITLE
Road Names Visible

### ISSUE THREAD

**Issue by py660** [codergautam/worldguessr#1]
The road names are visible on Google Maps Street View, making it very easy to guess the location. (Usually <100km)

**Comment by codergautam** [comment]
This is a known bug atm and has to do with the Map Embed API we use being less customizable. It's possible if we use the Map SDK but that has a cost per request. This is definitely something to research in the future for a solution.

**Comment by EnZon3** [comment]
I don't see this as an issue, in GeoGuessr typically I see the road names and it doesn't really affect the gameplay for me.

**Comment by codergautam** [comment]
Well many pro players are able to tell the location just from a street, ex. Sometimes it says the abbreviation of a state in a country. So we need to figure out a way to toggle this (believe Geoguessr has this)

**Comment by EnZon3** [comment]
> Well many pro players are able to tell the location just from a street, ex. Sometimes it says the abbreviation of a state in a country. So we need to figure out a way to toggle this (believe Geoguessr has this)

Yes, however that's perfectly fine. Once you become a pro finding those roads are easy. That's the fun, getting good. Buffing it will only make it worse for both new and pros alike.

**Comment by codergautam** [comment]
Road names are now togglable, I switched to the JS api but I don't know if this is allowed, I might have to switch it back

**Comment by EnZon3** [comment]
:+1:
