### ISSUE TITLE
Module not found: Can't resolve 'protobufjs/dist/minimal/protobuf.js'

### ISSUE THREAD

**Issue by NVJKKartik** [codergautam/worldguessr#30]
Import trace for requested module:
./node_modules/.pnpm/@cesium+engine@10.1.0/node_modules/@cesium/engine/index.js
./node_modules/.pnpm/cesium@1.120.0/node_modules/cesium/Source/Cesium.js
./components/cesium/CesiumWrapper.js
./pages/index.js

Got this error While trying to run 
`pnpm run dev`,
 there might be a dependency conflict I am missing Can you help?

**Comment by codergautam** [comment]
We actually don't use cesium anymore (it was for a homepage animation in the early days), weird that you get this error. I'll take a look

**Comment by m626zNq** [comment]
Researched this, seems like `npm install protobufjs@4.1.3` should fix this error.

**Comment by codergautam** [comment]
This error should no longer occur 

https://github.com/codergautam/worldguessr/commit/6b22fba35907ece04a02a2b36975d50b78dfeca4
