### ISSUE TITLE
Leaderbord

### ISSUE THREAD

**Issue by Gigaguesser** [codergautam/worldguessr#42]
My leaderbord is buged Like I Play a round I get Cup but the xp dosent Show on the leaderbord

**Comment by Gigaguesser** [comment]
BTW I am on mobile iPad

**Comment by codergautam** [comment]
The elo system will be launched on Friday which should hopefully resolve this issue.

**Comment by Gigaguesser** [comment]
Ok tyyy

**Comment by Gigaguesser** [comment]
BTW Great Game its good and chill to Play in scool
