### ISSUE TITLE
Suggestion - Remove trekker coverage

### ISSUE THREAD

**Issue by EnZon3** [codergautam/worldguessr#5]
I find issue in the fact that a lot of times I play, I get a lot of trekker coverage. (where people, not streetview cars take panoramas) I find this quite annoying since it's quite hard to pinpoint where you are being in buildings. Playing normal GeoGuessr I don't get this issue and it is much more fun to play.

**Comment by Rupledzo3072** [comment]
Agreed. Maybe keep a map with trekkers as an option, but I feel like the games should be played on only official Google StreetView coverage. Not sure how easy this would be to implement but I don't think it should be too bad.

**Comment by codergautam** [comment]
Will work on this!

**Comment by codergautam** [comment]
Attempted to fix this in commit https://github.com/codergautam/worldguessr/commit/641ba766894fddb50c8b86d204de8f0ef484f5fe

**Comment by EnZon3** [comment]
Will check if works
