### ISSUE TITLE
Suggestion - Allow to hide the map whenever you are not ready to make a guess

### ISSUE THREAD

**Issue by PupoSDC** [codergautam/worldguessr#9]
The map is always present which leads to terrible UX. In Ipads the game is virtually unplayable because the Map is always in first plane covering pretty much the whole screen 

![image](https://github.com/codergautam/worldguessr/assets/9625304/0f345055-4b88-4b58-9676-06e44dcd6e84)

Pease add a button to toggle the map for guessing being visible or not.

**Comment by codergautam** [comment]
It's an ipad thing, I will fix it soon.

**Comment by PupoSDC** [comment]
The IPAD is definetely critical, but even on a laptop, the minified map is simply too big and intrusive. 
<img width="1468" alt="Screenshot 2024-05-26 at 08 32 26" src="https://github.com/codergautam/worldguessr/assets/9625304/4eb20e77-c0a7-47b4-89ba-b9b3831c3d21">

As an example, The "giant on hover" makes it a bit frustrating to navigate to the right in the screenshot above

**Comment by codergautam** [comment]
This is now added, with the buttons on the top left of the minimap when hovered
